// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProjectMember(arg1) {
  return window['go']['main']['App']['AddProjectMember'](arg1);
}

export function AssignIssue(arg1) {
  return window['go']['main']['App']['AssignIssue'](arg1);
}

export function CreateComment(arg1) {
  return window['go']['main']['App']['CreateComment'](arg1);
}

export function CreateIssue(arg1) {
  return window['go']['main']['App']['CreateIssue'](arg1);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function CreateWorkflow(arg1) {
  return window['go']['main']['App']['CreateWorkflow'](arg1);
}

export function CreateWorkflowState(arg1) {
  return window['go']['main']['App']['CreateWorkflowState'](arg1);
}

export function CreateWorkflowTransition(arg1) {
  return window['go']['main']['App']['CreateWorkflowTransition'](arg1);
}

export function DeleteIssue(arg1) {
  return window['go']['main']['App']['DeleteIssue'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteWorkflowState(arg1) {
  return window['go']['main']['App']['DeleteWorkflowState'](arg1);
}

export function DeleteWorkflowTransition(arg1) {
  return window['go']['main']['App']['DeleteWorkflowTransition'](arg1);
}

export function GetAvailableTransitions(arg1) {
  return window['go']['main']['App']['GetAvailableTransitions'](arg1);
}

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function GetIssue(arg1) {
  return window['go']['main']['App']['GetIssue'](arg1);
}

export function GetIssueComments(arg1) {
  return window['go']['main']['App']['GetIssueComments'](arg1);
}

export function GetIssueStats(arg1) {
  return window['go']['main']['App']['GetIssueStats'](arg1);
}

export function GetProject(arg1) {
  return window['go']['main']['App']['GetProject'](arg1);
}

export function GetProjectMembers(arg1) {
  return window['go']['main']['App']['GetProjectMembers'](arg1);
}

export function GetWorkflow(arg1) {
  return window['go']['main']['App']['GetWorkflow'](arg1);
}

export function ListIssues(arg1) {
  return window['go']['main']['App']['ListIssues'](arg1);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ListUsers() {
  return window['go']['main']['App']['ListUsers']();
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function RemoveProjectMember(arg1, arg2) {
  return window['go']['main']['App']['RemoveProjectMember'](arg1, arg2);
}

export function TransitionIssue(arg1) {
  return window['go']['main']['App']['TransitionIssue'](arg1);
}

export function UpdateIssue(arg1) {
  return window['go']['main']['App']['UpdateIssue'](arg1);
}

export function UpdateProject(arg1) {
  return window['go']['main']['App']['UpdateProject'](arg1);
}
