// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {uuid} from '../models';

export function AddProjectMember(arg1:domain.AddProjectMemberRequest):Promise<void>;

export function AssignIssue(arg1:domain.AssignIssueRequest):Promise<domain.Issue>;

export function CreateComment(arg1:domain.CreateCommentRequest):Promise<domain.Comment>;

export function CreateIssue(arg1:domain.CreateIssueRequest):Promise<domain.Issue>;

export function CreateProject(arg1:domain.CreateProjectRequest):Promise<domain.Project>;

export function CreateWorkflow(arg1:domain.CreateWorkflowRequest):Promise<domain.Workflow>;

export function CreateWorkflowState(arg1:domain.CreateWorkflowStateRequest):Promise<domain.WorkflowState>;

export function CreateWorkflowTransition(arg1:domain.CreateWorkflowTransitionRequest):Promise<domain.WorkflowTransition>;

export function DeleteIssue(arg1:uuid.UUID):Promise<void>;

export function DeleteProject(arg1:uuid.UUID):Promise<void>;

export function DeleteWorkflowState(arg1:uuid.UUID):Promise<void>;

export function DeleteWorkflowTransition(arg1:uuid.UUID):Promise<void>;

export function GetAvailableTransitions(arg1:uuid.UUID):Promise<Array<domain.WorkflowTransition>>;

export function GetCurrentUser():Promise<domain.User>;

export function GetIssue(arg1:uuid.UUID):Promise<domain.Issue>;

export function GetIssueComments(arg1:uuid.UUID):Promise<Array<domain.Comment>>;

export function GetIssueStats(arg1:uuid.UUID):Promise<domain.ProjectStats>;

export function GetProject(arg1:uuid.UUID):Promise<domain.Project>;

export function GetProjectMembers(arg1:uuid.UUID):Promise<Array<domain.ProjectMember>>;

export function GetWorkflow(arg1:uuid.UUID):Promise<domain.Workflow>;

export function ListIssues(arg1:domain.IssueFilter):Promise<Record<string, any>>;

export function ListProjects():Promise<Array<domain.Project>>;

export function ListUsers():Promise<Array<domain.User>>;

export function Login(arg1:string):Promise<domain.User>;

export function RemoveProjectMember(arg1:uuid.UUID,arg2:uuid.UUID):Promise<void>;

export function TransitionIssue(arg1:domain.TransitionIssueRequest):Promise<domain.Issue>;

export function UpdateIssue(arg1:domain.UpdateIssueRequest):Promise<domain.Issue>;

export function UpdateProject(arg1:domain.UpdateProjectRequest):Promise<domain.Project>;
